server.port=8888
#register it as Eureka client , with Eureka server Url
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#Configure the routes for Inventory MS 
spring.cloud.gateway.server.webflux.routes[0].id=id1
spring.cloud.gateway.server.webflux.routes[0].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/inventory/**
# StripPrefix removes the specified number of path segments from the beginning of the URL.
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

#Configure the routes for Order MS 
spring.cloud.gateway.server.webflux.routes[1].id=id2
spring.cloud.gateway.server.webflux.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/orders/**
# StripPrefix removes the specified number of path segments from the beginning of the URL.
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1



