#Optional Rabbit MQ properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#Rabbit MQ Subscriber props
routing.exchange=order.exchange
routing.key=order.*
routing.queue=order.queue
