server.port=9090

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password={cipher}94e43c49f5a036863c110aab5636a106fa660f623aa503dc87210acadb76dd56
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Eureka client property  to specify that the IP address should be used in preference to the hostname reported by the OS.
eureka.instance.prefer-ip-address=true


#required property for adding a binding with RabbitMq
spring.cloud.stream.default.group=orders

#contact info in case of issues, to test auto Refresh w/o restarting the MS
order.message=Welcome To Order Service
order.contactDetails.name=Ravi Patil
order.contactDetails.email=ravi1@gmail.com
order.onCallSupport[0]=9223456677
order.onCallSupport[1]=9333456679

#Enable Actuator’s  end points
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#specifically enable monitoring of circuitbreakers end points
management.health.circuitbreakers.enabled=true

#circuit breaker related  props
#circuit breaker config for  the specific instance - name of CircuitBreaker (eg - stock) 

#registers the circuit breaker with Spring Boot Actuator.
resilience4j.circuitbreaker.instances.stock.register-health-indicator=true

#Looks  at the last N calls.
resilience4j.circuitbreaker.instances.stock.sliding-window-type=COUNT_BASED

#This tells Resilience4j how many recent calls(5) it should remember(discarding the oldest result)
resilience4j.circuitbreaker.instances.stock.sliding-window-size=5

#The circuit breaker will not calculate the failure rate until at least 3 calls have occurred.
resilience4j.circuitbreaker.instances.stock.minimum-number-of-calls=3

#If failures are 50% or more, the breaker opens.
resilience4j.circuitbreaker.instances.stock.failure-rate-threshold=50

# After 10s circuit will go to half open state
resilience4j.circuitbreaker.instances.stock.wait-duration-in-open-state=10s

#no of allowed calls When the circuit enters HALF_OPEN - 2
resilience4j.circuitbreaker.instances.demo.permitted-number-of-calls-in-half-open-state=2

#After wait-duration-in-open-state expires, circuit  automatically changes to half open state
resilience4j.circuitbreaker.instances.stock.automatic-transition-from-open-to-half-open-enabled=true




