server.port=9090

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password={cipher}94e43c49f5a036863c110aab5636a106fa660f623aa503dc87210acadb76dd56
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Eureka client property  to specify that the IP address should be used in preference to the hostname reported by the OS.
eureka.instance.prefer-ip-address=true
#Enable Actuator’s  end points
management.endpoints.web.exposure.include=*

#required property for adding a binding with RabbitMq
spring.cloud.stream.default.group=configserver


